platform :ios, '15.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'react_native_web_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => true
  )

  # Uncomment the next line if you don't want to use Flipper
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end